version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./docker/postgres_volume:/var/lib/postgresql/data
  pgadm:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=sl.biano28@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
  